### ISSUE TITLE
輸入開始與結束日期要按很久

### ISSUE THREAD

**Issue by hansen033** [youranimes/web-status#43]
希望可以直接輸入日期，或是能夠選擇年分，不然一直點需要花上一點時間

**Comment by youranimes** [comment]
@hansen033 你好，感謝你的建議，已增加下拉式表單來選擇特定的年月份。使用上若有什麼問題，再麻煩你再次反應，謝謝你喔～ （附圖為下拉式選單的樣式）

![截圖 2024-10-21 晚上10 23 46](https://github.com/user-attachments/assets/1183d930-f434-4551-b44b-d479e5cef7ef)
![截圖 2024-10-21 晚上10 27 26](https://github.com/user-attachments/assets/34b9cb91-c8b6-47a7-9573-07a96e965bad)
