### ISSUE TITLE
修正日期自動更改的問題

### ISSUE THREAD

**Issue by yochen16** [youranimes/web-status#65]
希望可以修正觀看日期不時會在更動並儲存觀看記錄後自動往後移一天的問題。

**Comment by youranimes** [comment]
不好意思，造成你的困擾！可否請你提供更詳細的說明，或者分享操作的步驟，讓我可以復現這個問題，以便進行修復和確認。非常感謝你的協助！

**Comment by yochen16** [comment]
你好，日前有發現在更改觀看集數（例如從7調整至8）後儲存時，偶爾會發生「開始觀看」日期自動後移一日（如原本是2024-10-17，即變更成2024-10-18）。
目前發現這個問題從手機和電腦都會發生，且由於是按下儲存按鈕後自動更改的，所以確定不是誤觸導致，謝謝！

**Comment by youranimes** [comment]
感謝提供，會儘速修正這個問題。

**Comment by youranimes** [comment]
非常感謝你的回報，問題已修正，再麻煩你試看看。

**Comment by yochen16** [comment]
感謝修正，目前測試沒有問題，辛苦了！

**Comment by youranimes** [comment]
不會，反而要感謝你的回饋！由於網站是我個人獨立開發，功能測試難免有盲點。如果未來使用上還有其他問題，也請隨時告訴我，非常感謝～
